# 元素周期表数据，供 agent.py 导入
PERIODIC_TABLE = [
    {"name": "Hydrogen", "symbol": "H", "atomic_number": 1,
     "atomic_weight": 1.008, "group": 1, "period": 1, "chinese_name": "氢"},
    {"name": "Helium", "symbol": "He", "atomic_number": 2,
     "atomic_weight": 4.0026, "group": 18, "period": 1, "chinese_name": "氦"},
    {"name": "Lithium", "symbol": "Li", "atomic_number": 3,
     "atomic_weight": 6.94, "group": 1, "period": 2, "chinese_name": "锂"},
    {"name": "Beryllium", "symbol": "Be", "atomic_number": 4,
     "atomic_weight": 9.0122, "group": 2, "period": 2, "chinese_name": "铍"},
    {"name": "Boron", "symbol": "B", "atomic_number": 5,
     "atomic_weight": 10.81, "group": 13, "period": 2, "chinese_name": "硼"},
    {"name": "Carbon", "symbol": "C", "atomic_number": 6,
     "atomic_weight": 12.011, "group": 14, "period": 2, "chinese_name": "碳"},
    {"name": "Nitrogen", "symbol": "N", "atomic_number": 7,
     "atomic_weight": 14.007, "group": 15, "period": 2, "chinese_name": "氮"},
    {"name": "Oxygen", "symbol": "O", "atomic_number": 8,
     "atomic_weight": 15.999, "group": 16, "period": 2, "chinese_name": "氧"},
    {"name": "Fluorine", "symbol": "F", "atomic_number": 9,
     "atomic_weight": 18.998, "group": 17, "period": 2, "chinese_name": "氟"},
    {"name": "Neon", "symbol": "Ne", "atomic_number": 10,
     "atomic_weight": 20.180, "group": 18, "period": 2, "chinese_name": "氖"},
    {"name": "Sodium", "symbol": "Na", "atomic_number": 11,
     "atomic_weight": 22.990, "group": 1, "period": 3, "chinese_name": "钠"},
    {"name": "Magnesium", "symbol": "Mg", "atomic_number": 12,
     "atomic_weight": 24.305, "group": 2, "period": 3, "chinese_name": "镁"},
    {"name": "Aluminum", "symbol": "Al", "atomic_number": 13,
     "atomic_weight": 26.982, "group": 13, "period": 3, "chinese_name": "铝"},
    {"name": "Silicon", "symbol": "Si", "atomic_number": 14,
     "atomic_weight": 28.085, "group": 14, "period": 3, "chinese_name": "硅"},
    {"name": "Phosphorus", "symbol": "P", "atomic_number": 15,
     "atomic_weight": 30.974, "group": 15, "period": 3, "chinese_name": "磷"},
    {"name": "Sulfur", "symbol": "S", "atomic_number": 16,
     "atomic_weight": 32.06, "group": 16, "period": 3, "chinese_name": "硫"},
    {"name": "Chlorine", "symbol": "Cl", "atomic_number": 17,
     "atomic_weight": 35.45, "group": 17, "period": 3, "chinese_name": "氯"},
    {"name": "Argon", "symbol": "Ar", "atomic_number": 18,
     "atomic_weight": 39.948, "group": 18, "period": 3, "chinese_name": "氩"},
    {"name": "Potassium", "symbol": "K", "atomic_number": 19,
     "atomic_weight": 39.098, "group": 1, "period": 4, "chinese_name": "钾"},
    {"name": "Calcium", "symbol": "Ca", "atomic_number": 20,
     "atomic_weight": 40.078, "group": 2, "period": 4, "chinese_name": "钙"},
    {"name": "Scandium", "symbol": "Sc", "atomic_number": 21,
     "atomic_weight": 44.956, "group": 3, "period": 4, "chinese_name": "钪"},
    {"name": "Titanium", "symbol": "Ti", "atomic_number": 22,
     "atomic_weight": 47.867, "group": 4, "period": 4, "chinese_name": "钛"},
    {"name": "Vanadium", "symbol": "V", "atomic_number": 23,
     "atomic_weight": 50.942, "group": 5, "period": 4, "chinese_name": "钒"},
    {"name": "Chromium", "symbol": "Cr", "atomic_number": 24,
     "atomic_weight": 51.996, "group": 6, "period": 4, "chinese_name": "铬"},
    {"name": "Manganese", "symbol": "Mn", "atomic_number": 25,
     "atomic_weight": 54.938, "group": 7, "period": 4, "chinese_name": "锰"},
    {"name": "Iron", "symbol": "Fe", "atomic_number": 26,
     "atomic_weight": 55.845, "group": 8, "period": 4, "chinese_name": "铁"},
    {"name": "Cobalt", "symbol": "Co", "atomic_number": 27,
     "atomic_weight": 58.933, "group": 9, "period": 4, "chinese_name": "钴"},
    {"name": "Nickel", "symbol": "Ni", "atomic_number": 28,
     "atomic_weight": 58.693, "group": 10, "period": 4, "chinese_name": "镍"},
    {"name": "Copper", "symbol": "Cu", "atomic_number": 29,
     "atomic_weight": 63.546, "group": 11, "period": 4, "chinese_name": "铜"},
    {"name": "Zinc", "symbol": "Zn", "atomic_number": 30,
     "atomic_weight": 65.38, "group": 12, "period": 4, "chinese_name": "锌"},
    {"name": "Gallium", "symbol": "Ga", "atomic_number": 31,
     "atomic_weight": 69.723, "group": 13, "period": 4, "chinese_name": "镓"},
    {"name": "Germanium", "symbol": "Ge", "atomic_number": 32,
     "atomic_weight": 72.630, "group": 14, "period": 4, "chinese_name": "锗"},
    {"name": "Arsenic", "symbol": "As", "atomic_number": 33,
     "atomic_weight": 74.922, "group": 15, "period": 4, "chinese_name": "砷"},
    {"name": "Selenium", "symbol": "Se", "atomic_number": 34,
     "atomic_weight": 78.971, "group": 16, "period": 4, "chinese_name": "硒"},
    {"name": "Bromine", "symbol": "Br", "atomic_number": 35,
     "atomic_weight": 79.904, "group": 17, "period": 4, "chinese_name": "溴"},
    {"name": "Krypton", "symbol": "Kr", "atomic_number": 36,
     "atomic_weight": 83.798, "group": 18, "period": 4, "chinese_name": "氪"},
    {"name": "Rubidium", "symbol": "Rb", "atomic_number": 37,
     "atomic_weight": 85.468, "group": 1, "period": 5, "chinese_name": "铷"},
    {"name": "Strontium", "symbol": "Sr", "atomic_number": 38,
     "atomic_weight": 87.62, "group": 2, "period": 5, "chinese_name": "锶"},
    {"name": "Yttrium", "symbol": "Y", "atomic_number": 39,
     "atomic_weight": 88.906, "group": 3, "period": 5, "chinese_name": "钇"},
    {"name": "Zirconium", "symbol": "Zr", "atomic_number": 40,
     "atomic_weight": 91.224, "group": 4, "period": 5, "chinese_name": "锆"},
    {"name": "Niobium", "symbol": "Nb", "atomic_number": 41,
     "atomic_weight": 92.906, "group": 5, "period": 5, "chinese_name": "铌"},
    {"name": "Molybdenum", "symbol": "Mo", "atomic_number": 42,
     "atomic_weight": 95.95, "group": 6, "period": 5, "chinese_name": "钼"},
    {"name": "Technetium", "symbol": "Tc", "atomic_number": 43,
     "atomic_weight": 98, "group": 7, "period": 5, "chinese_name": "锝"},
    {"name": "Ruthenium", "symbol": "Ru", "atomic_number": 44,
     "atomic_weight": 101.07, "group": 8, "period": 5, "chinese_name": "钌"},
    {"name": "Rhodium", "symbol": "Rh", "atomic_number": 45,
     "atomic_weight": 102.91, "group": 9, "period": 5, "chinese_name": "铑"},
    {"name": "Palladium", "symbol": "Pd", "atomic_number": 46,
     "atomic_weight": 106.42, "group": 10, "period": 5, "chinese_name": "钯"},
    {"name": "Silver", "symbol": "Ag", "atomic_number": 47,
     "atomic_weight": 107.87, "group": 11, "period": 5, "chinese_name": "银"},
    {"name": "Cadmium", "symbol": "Cd", "atomic_number": 48,
     "atomic_weight": 112.41, "group": 12, "period": 5, "chinese_name": "镉"},
    {"name": "Indium", "symbol": "In", "atomic_number": 49,
     "atomic_weight": 114.82, "group": 13, "period": 5, "chinese_name": "铟"},
    {"name": "Tin", "symbol": "Sn", "atomic_number": 50,
     "atomic_weight": 118.71, "group": 14, "period": 5, "chinese_name": "锡"},
    {"name": "Antimony", "symbol": "Sb", "atomic_number": 51,
     "atomic_weight": 121.76, "group": 15, "period": 5, "chinese_name": "锑"},
    {"name": "Tellurium", "symbol": "Te", "atomic_number": 52,
     "atomic_weight": 127.60, "group": 16, "period": 5, "chinese_name": "碲"},
    {"name": "Iodine", "symbol": "I", "atomic_number": 53,
     "atomic_weight": 126.90, "group": 17, "period": 5, "chinese_name": "碘"},
    {"name": "Xenon", "symbol": "Xe", "atomic_number": 54,
     "atomic_weight": 131.29, "group": 18, "period": 5, "chinese_name": "氙"},
    {"name": "Cesium", "symbol": "Cs", "atomic_number": 55,
     "atomic_weight": 132.91, "group": 1, "period": 6, "chinese_name": "铯"},
    {"name": "Barium", "symbol": "Ba", "atomic_number": 56,
     "atomic_weight": 137.33, "group": 2, "period": 6, "chinese_name": "钡"},
    {"name": "Lanthanum", "symbol": "La", "atomic_number": 57,
     "atomic_weight": 138.91, "group": 3, "period": 6, "chinese_name": "镧"},
    {"name": "Cerium", "symbol": "Ce", "atomic_number": 58,
     "atomic_weight": 140.12, "group": 4, "period": 6, "chinese_name": "铈"},
    {"name": "Praseodymium", "symbol": "Pr", "atomic_number": 59,
     "atomic_weight": 140.91, "group": 5, "period": 6, "chinese_name": "镨"},
    {"name": "Neodymium", "symbol": "Nd", "atomic_number": 60,
     "atomic_weight": 144.24, "group": 6, "period": 6, "chinese_name": "钕"},
    {"name": "Promethium", "symbol": "Pm", "atomic_number": 61,
     "atomic_weight": 145, "group": 7, "period": 6, "chinese_name": "钷"},
    {"name": "Samarium", "symbol": "Sm", "atomic_number": 62,
     "atomic_weight": 150.36, "group": 8, "period": 6, "chinese_name": "钐"},
    {"name": "Europium", "symbol": "Eu", "atomic_number": 63,
     "atomic_weight": 151.96, "group": 9, "period": 6, "chinese_name": "铕"},
    {"name": "Gadolinium", "symbol": "Gd", "atomic_number": 64,
     "atomic_weight": 157.25, "group": 10, "period": 6, "chinese_name": "钆"},
    {"name": "Terbium", "symbol": "Tb", "atomic_number": 65,
     "atomic_weight": 158.93, "group": 11, "period": 6, "chinese_name": "铽"},
    {"name": "Dysprosium", "symbol": "Dy", "atomic_number": 66,
     "atomic_weight": 162.50, "group": 12, "period": 6, "chinese_name": "镝"},
    {"name": "Holmium", "symbol": "Ho", "atomic_number": 67,
     "atomic_weight": 164.93, "group": 13, "period": 6, "chinese_name": "钬"},
    {"name": "Erbium", "symbol": "Er", "atomic_number": 68,
     "atomic_weight": 167.26, "group": 14, "period": 6, "chinese_name": "铒"},
    {"name": "Thulium", "symbol": "Tm", "atomic_number": 69,
     "atomic_weight": 168.93, "group": 15, "period": 6, "chinese_name": "铥"},
    {"name": "Ytterbium", "symbol": "Yb", "atomic_number": 70,
     "atomic_weight": 173.05, "group": 16, "period": 6, "chinese_name": "镱"},
    {"name": "Lutetium", "symbol": "Lu", "atomic_number": 71,
     "atomic_weight": 174.97, "group": 17, "period": 6, "chinese_name": "镥"},
    {"name": "Hafnium", "symbol": "Hf", "atomic_number": 72,
     "atomic_weight": 178.49, "group": 4, "period": 6, "chinese_name": "铪"},
    {"name": "Tantalum", "symbol": "Ta", "atomic_number": 73,
     "atomic_weight": 180.95, "group": 5, "period": 6, "chinese_name": "钽"},
    {"name": "Tungsten", "symbol": "W", "atomic_number": 74,
     "atomic_weight": 183.84, "group": 6, "period": 6, "chinese_name": "钨"},
    {"name": "Rhenium", "symbol": "Re", "atomic_number": 75,
     "atomic_weight": 186.21, "group": 7, "period": 6, "chinese_name": "铼"},
    {"name": "Osmium", "symbol": "Os", "atomic_number": 76,
     "atomic_weight": 190.23, "group": 8, "period": 6, "chinese_name": "锇"},
    {"name": "Iridium", "symbol": "Ir", "atomic_number": 77,
     "atomic_weight": 192.22, "group": 9, "period": 6, "chinese_name": "铱"},
    {"name": "Platinum", "symbol": "Pt", "atomic_number": 78,
     "atomic_weight": 195.08, "group": 10, "period": 6, "chinese_name": "铂"},
    {"name": "Gold", "symbol": "Au", "atomic_number": 79,
     "atomic_weight": 196.97, "group": 11, "period": 6, "chinese_name": "金"},
    {"name": "Mercury", "symbol": "Hg", "atomic_number": 80,
     "atomic_weight": 200.59, "group": 12, "period": 6, "chinese_name": "汞"},
    {"name": "Thallium", "symbol": "Tl", "atomic_number": 81,
     "atomic_weight": 204.38, "group": 13, "period": 6, "chinese_name": "铊"},
    {"name": "Lead", "symbol": "Pb", "atomic_number": 82,
     "atomic_weight": 207.2, "group": 14, "period": 6, "chinese_name": "铅"},
    {"name": "Bismuth", "symbol": "Bi", "atomic_number": 83,
     "atomic_weight": 208.98, "group": 15, "period": 6, "chinese_name": "铋"},
    {"name": "Polonium", "symbol": "Po", "atomic_number": 84,
     "atomic_weight": 209, "group": 16, "period": 6, "chinese_name": "钋"},
    {"name": "Astatine", "symbol": "At", "atomic_number": 85,
     "atomic_weight": 210, "group": 17, "period": 6, "chinese_name": "砹"},
    {"name": "Radon", "symbol": "Rn", "atomic_number": 86,
     "atomic_weight": 222, "group": 18, "period": 6, "chinese_name": "氡"},
    {"name": "Francium", "symbol": "Fr", "atomic_number": 87,
     "atomic_weight": 223, "group": 1, "period": 7, "chinese_name": "钫"},
    {"name": "Radium", "symbol": "Ra", "atomic_number": 88,
     "atomic_weight": 226, "group": 2, "period": 7, "chinese_name": "镭"},
    {"name": "Actinium", "symbol": "Ac", "atomic_number": 89,
     "atomic_weight": 227, "group": 3, "period": 7, "chinese_name": "锕"},
    {"name": "Thorium", "symbol": "Th", "atomic_number": 90,
     "atomic_weight": 232.04, "group": 4, "period": 7, "chinese_name": "钍"},
    {"name": "Protactinium", "symbol": "Pa", "atomic_number": 91,
     "atomic_weight": 231.04, "group": 5, "period": 7, "chinese_name": "镤"},
    {"name": "Uranium", "symbol": "U", "atomic_number": 92,
     "atomic_weight": 238.03, "group": 6, "period": 7, "chinese_name": "铀"},
    {"name": "Neptunium", "symbol": "Np", "atomic_number": 93,
     "atomic_weight": 237, "group": 7, "period": 7, "chinese_name": "镎"},
    {"name": "Plutonium", "symbol": "Pu", "atomic_number": 94,
     "atomic_weight": 244, "group": 8, "period": 7, "chinese_name": "钚"},
    {"name": "Americium", "symbol": "Am", "atomic_number": 95,
     "atomic_weight": 243, "group": 9, "period": 7, "chinese_name": "镅"},
    {"name": "Curium", "symbol": "Cm", "atomic_number": 96,
     "atomic_weight": 247, "group": 10, "period": 7, "chinese_name": "锔"},
    {"name": "Berkelium", "symbol": "Bk", "atomic_number": 97,
     "atomic_weight": 247, "group": 11, "period": 7, "chinese_name": "锫"},
    {"name": "Californium", "symbol": "Cf", "atomic_number": 98,
     "atomic_weight": 251, "group": 12, "period": 7, "chinese_name": "锎"},
    {"name": "Einsteinium", "symbol": "Es", "atomic_number": 99,
     "atomic_weight": 252, "group": 13, "period": 7, "chinese_name": "锿"},
    {"name": "Fermium", "symbol": "Fm", "atomic_number": 100,
     "atomic_weight": 257, "group": 14, "period": 7, "chinese_name": "镄"},
    {"name": "Mendelevium", "symbol": "Md", "atomic_number": 101,
     "atomic_weight": 258, "group": 15, "period": 7, "chinese_name": "钔"},
    {"name": "Nobelium", "symbol": "No", "atomic_number": 102,
     "atomic_weight": 259, "group": 16, "period": 7, "chinese_name": "锘"},
    {"name": "Lawrencium", "symbol": "Lr", "atomic_number": 103,
     "atomic_weight": 266, "group": 17, "period": 7, "chinese_name": "铹"},
    {"name": "Rutherfordium", "symbol": "Rf", "atomic_number": 104,
     "atomic_weight": 267, "group": 4, "period": 7, "chinese_name": "𬬻"},
    {"name": "Dubnium", "symbol": "Db", "atomic_number": 105,
     "atomic_weight": 270, "group": 5, "period": 7, "chinese_name": "𬭊"},
    {"name": "Seaborgium", "symbol": "Sg", "atomic_number": 106,
     "atomic_weight": 271, "group": 6, "period": 7, "chinese_name": "𬭳"},
    {"name": "Bohrium", "symbol": "Bh", "atomic_number": 107,
     "atomic_weight": 270, "group": 7, "period": 7, "chinese_name": "𬭛"},
    {"name": "Hassium", "symbol": "Hs", "atomic_number": 108,
     "atomic_weight": 277, "group": 8, "period": 7, "chinese_name": "𬭶"},
    {"name": "Meitnerium", "symbol": "Mt", "atomic_number": 109,
     "atomic_weight": 278, "group": 9, "period": 7, "chinese_name": "鿏"},
    {"name": "Darmstadtium", "symbol": "Ds", "atomic_number": 110,
     "atomic_weight": 281, "group": 10, "period": 7, "chinese_name": "鿔"},
    {"name": "Roentgenium", "symbol": "Rg", "atomic_number": 111,
     "atomic_weight": 282, "group": 11, "period": 7, "chinese_name": "鿭"},
    {"name": "Copernicium", "symbol": "Cn", "atomic_number": 112,
     "atomic_weight": 285, "group": 12, "period": 7, "chinese_name": "鿬"},
    {"name": "Nihonium", "symbol": "Nh", "atomic_number": 113,
     "atomic_weight": 286, "group": 13, "period": 7, "chinese_name": "鉨"},
    {"name": "Flerovium", "symbol": "Fl", "atomic_number": 114,
     "atomic_weight": 289, "group": 14, "period": 7, "chinese_name": "鈇"},
    {"name": "Moscovium", "symbol": "Mc", "atomic_number": 115,
     "atomic_weight": 290, "group": 15, "period": 7, "chinese_name": "镆"},
    {"name": "Livermorium", "symbol": "Lv", "atomic_number": 116,
     "atomic_weight": 293, "group": 16, "period": 7, "chinese_name": "鉝"},
    {"name": "Tennessine", "symbol": "Ts", "atomic_number": 117,
     "atomic_weight": 294, "group": 17, "period": 7, "chinese_name": "鿬"},
    {"name": "Oganesson", "symbol": "Og", "atomic_number": 118,
     "atomic_weight": 294, "group": 18, "period": 7, "chinese_name": "鿫"},
]
